apiVersion: v1
kind: Namespace
metadata:
  name: swisscom-service-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swisscom-service-broker-redis
  namespace: swisscom-service-broker
  labels:
    app.kubernetes.io/instance: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: redis
    spec:
      serviceAccountName: swisscom-service-broker
      containers:
        - name: swisscom-service-broker
          image: docker.io/vshn/swisscom-service-broker:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: OSB_SERVICE_IDS
              value: INSERT_SERVICE_ID_HERE # redis
            - name: OSB_USERNAME
              value: test
            - name: OSB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: swisscom-service-broker
                  key: password
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
