apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-redis.yaml
  - rbac.yaml
  - service_account.yaml
  - service-redis.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: swisscom-service-broker
