resources:
  - ../../deploy/base
  - secret.yaml
namespace: swisscom-service-broker

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: e2e
patches:
  - path: deployment.yaml
