resources:
  - ../../deploy/base
  - secret.yaml
patchesStrategicMerge:
  - deployment.yaml
namespace: swisscom-service-broker

commonLabels:
  app.kubernetes.io/name: e2e
  app.kubernetes.io/managed-by: kustomize
